---
title: "R Notebook"
output: html_notebook
---



```{r}
#install.packages("dslabs")
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("cowplot")
library(dslabs)
library(tidyverse)
library(ggplot2)
library(cowplot)
```
 



```{r}
heights %>% filter(sex == 'Female') %>% ggplot() + geom_histogram(aes(height)) + labs(title = "Female")
heights %>% filter(sex == 'Male') %>% ggplot() + geom_histogram(aes(height)) + labs(title = "Male")

results <- heights %>% group_by(sex) %>% summarize(ave = mean(height), sd = sd(height))

results_W <- results %>% filter(sex == 'Female')

pnorm(61, results_W$ave, results_W$sd)


#히스토그램을 통해 살펴본 결과 male과 female 모두 정규분포에 가까운 분포를 뛰고 있음을 알 수 있다. 그래서 두 그룹을 모두 정규분포로 가정하고, mean과 sd를 results값에 sex별로 저장하였다. 그 후 pnorm을 사용하여 female이 61cm보다 작을 확률을 구하였다.
```

```{r}
p <- 3/(19+16+3)
N <- 1000
B <- 1000

set.seed(1)
x <- sample(c(15,-1), N, replace = TRUE, prob = c(p, 1-p))
S <- sum(x)

results <- data.frame(ES = N*(15*p -(1-p)), SeS = sqrt(N)*16*sqrt(p*(1-p)))


my_function <- function(N){
  x <- sample(c(15, -1), N, replace = TRUE, prob = c(p, 1-p))
  sum(x)
}

Monte <- replicate(B, my_function(N))
Monte_result <- data.frame(ES = mean(Monte), SeS= sd(Monte))

rbind(results, Monte_result)
#result값은 이론적인 S의 expected value와 standard deviation을 입력하였고, Monte_result에는 Monte Carlo를 통해 구한 실험적인 standard deviation과 expected value를 입력하였다. 비교 결과 두 값은 거의 비슷하다는 것을 통하여 어떤 사건의 시행 횟수N이 충분히 크면 그 기대값과 sd가 이론값과 비슷하다는 CLT 법칙을 확인할 수 있다.
```

```{r}
p <- 0.45
poll <- function(N){
  x <-sample(c(1,0), N, replace = TRUE, prob = c(p, 1-p))
  sum(x)
}

poll2 <- function(N,B){
  x<-replicate(B, poll(N))
  print(c(mean(x), sd(x)))
  }

d <- data.frame(A = poll2(10,100), B = poll2(10,10000), C = poll2(1000,100), D = poll2(1000,10000))


EX <- function(N){N*p}
SE <- function(N){sqrt(N)*sqrt(p*(1-p))}

d1 <- data.frame(A = c(EX(10), SE(10)), B = c(EX(10), SE(10)), C = c(EX(1000), SE(1000)), D = c(EX(1000), SE(1000)))

rbind(d, d1)


#이론값과 실제값을 비교한 결과, N의 값이 커질수록 이론값과 실제값이 비슷해진다. 
```

